name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        gtk_version: [2, 3]
        include:
          - gimp_git_tag: 'GIMP_2_10_22'
            gtk_version: ''

    container:
      image: photoflow/docker-centos7-gimp
      env:
        GTK_VERSION: ${{ matrix.gtk_version }}
        GIMP_GIT_TAG: ${{ matrix.gimp_git_tag }}
        BABL_GIT_TAG: 'BABL_0_1_82'
        GEGL_GIT_TAG: 'GEGL_0_4_26'

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: build AppImage
        run: |
          ln -s "$PWD" /sources
          exec /sources/mkappimage.sh

      - name: archive built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gimp-appimage
          path: out/*
          retention-days: 7

  upload:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: retrieve artifacts
        uses: actions/download-artifact@v2
        with:
          name: gimp-appimage
          path: out/

      - name: dump files
        run:  ls -lh out/

      - name: retrieve upload tool
        run: wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh

      - name: upload built files
        run: bash ./upload_rotate.sh "continuous" out/*
        env:
          TRAVIS_REPO_SLUG: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}